// Generated by gencpp from file config/param.msg
// DO NOT EDIT!


#ifndef CONFIG_MESSAGE_PARAM_H
#define CONFIG_MESSAGE_PARAM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace config
{
template <class ContainerAllocator>
struct param_
{
  typedef param_<ContainerAllocator> Type;

  param_()
    : NMS_THRESH(0.0)
    , CONF_THRESH(0.0)
    , k_volleyball(0)
    , k_basketball(0)
    , k_basket(0)
    , k_mark(0)
    , if_shot(false)
    , if_show(false)
    , k_x0(0.0)
    , k_y0(0.0)
    , k_z0(0.0)
    , k_x1(0.0)
    , k_y1(0.0)
    , k_z1(0.0)
    , k_test(0.0)  {
    }
  param_(const ContainerAllocator& _alloc)
    : NMS_THRESH(0.0)
    , CONF_THRESH(0.0)
    , k_volleyball(0)
    , k_basketball(0)
    , k_basket(0)
    , k_mark(0)
    , if_shot(false)
    , if_show(false)
    , k_x0(0.0)
    , k_y0(0.0)
    , k_z0(0.0)
    , k_x1(0.0)
    , k_y1(0.0)
    , k_z1(0.0)
    , k_test(0.0)  {
  (void)_alloc;
    }



   typedef float _NMS_THRESH_type;
  _NMS_THRESH_type NMS_THRESH;

   typedef float _CONF_THRESH_type;
  _CONF_THRESH_type CONF_THRESH;

   typedef int32_t _k_volleyball_type;
  _k_volleyball_type k_volleyball;

   typedef int32_t _k_basketball_type;
  _k_basketball_type k_basketball;

   typedef int32_t _k_basket_type;
  _k_basket_type k_basket;

   typedef int32_t _k_mark_type;
  _k_mark_type k_mark;

   typedef uint8_t _if_shot_type;
  _if_shot_type if_shot;

   typedef uint8_t _if_show_type;
  _if_show_type if_show;

   typedef double _k_x0_type;
  _k_x0_type k_x0;

   typedef double _k_y0_type;
  _k_y0_type k_y0;

   typedef double _k_z0_type;
  _k_z0_type k_z0;

   typedef double _k_x1_type;
  _k_x1_type k_x1;

   typedef double _k_y1_type;
  _k_y1_type k_y1;

   typedef double _k_z1_type;
  _k_z1_type k_z1;

   typedef double _k_test_type;
  _k_test_type k_test;





  typedef boost::shared_ptr< ::config::param_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::config::param_<ContainerAllocator> const> ConstPtr;

}; // struct param_

typedef ::config::param_<std::allocator<void> > param;

typedef boost::shared_ptr< ::config::param > paramPtr;
typedef boost::shared_ptr< ::config::param const> paramConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::config::param_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::config::param_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::config::param_<ContainerAllocator1> & lhs, const ::config::param_<ContainerAllocator2> & rhs)
{
  return lhs.NMS_THRESH == rhs.NMS_THRESH &&
    lhs.CONF_THRESH == rhs.CONF_THRESH &&
    lhs.k_volleyball == rhs.k_volleyball &&
    lhs.k_basketball == rhs.k_basketball &&
    lhs.k_basket == rhs.k_basket &&
    lhs.k_mark == rhs.k_mark &&
    lhs.if_shot == rhs.if_shot &&
    lhs.if_show == rhs.if_show &&
    lhs.k_x0 == rhs.k_x0 &&
    lhs.k_y0 == rhs.k_y0 &&
    lhs.k_z0 == rhs.k_z0 &&
    lhs.k_x1 == rhs.k_x1 &&
    lhs.k_y1 == rhs.k_y1 &&
    lhs.k_z1 == rhs.k_z1 &&
    lhs.k_test == rhs.k_test;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::config::param_<ContainerAllocator1> & lhs, const ::config::param_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace config

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::config::param_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::config::param_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::config::param_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::config::param_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::config::param_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::config::param_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::config::param_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4507b4f03a0f3c68cc9f0657404bb3a2";
  }

  static const char* value(const ::config::param_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4507b4f03a0f3c68ULL;
  static const uint64_t static_value2 = 0xcc9f0657404bb3a2ULL;
};

template<class ContainerAllocator>
struct DataType< ::config::param_<ContainerAllocator> >
{
  static const char* value()
  {
    return "config/param";
  }

  static const char* value(const ::config::param_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::config::param_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 NMS_THRESH\n"
"float32 CONF_THRESH\n"
"int32 k_volleyball\n"
"int32 k_basketball\n"
"int32 k_basket\n"
"int32 k_mark\n"
"bool if_shot\n"
"bool if_show\n"
"float64 k_x0\n"
"float64 k_y0\n"
"float64 k_z0\n"
"float64 k_x1\n"
"float64 k_y1\n"
"float64 k_z1\n"
"float64 k_test\n"
;
  }

  static const char* value(const ::config::param_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::config::param_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.NMS_THRESH);
      stream.next(m.CONF_THRESH);
      stream.next(m.k_volleyball);
      stream.next(m.k_basketball);
      stream.next(m.k_basket);
      stream.next(m.k_mark);
      stream.next(m.if_shot);
      stream.next(m.if_show);
      stream.next(m.k_x0);
      stream.next(m.k_y0);
      stream.next(m.k_z0);
      stream.next(m.k_x1);
      stream.next(m.k_y1);
      stream.next(m.k_z1);
      stream.next(m.k_test);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct param_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::config::param_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::config::param_<ContainerAllocator>& v)
  {
    s << indent << "NMS_THRESH: ";
    Printer<float>::stream(s, indent + "  ", v.NMS_THRESH);
    s << indent << "CONF_THRESH: ";
    Printer<float>::stream(s, indent + "  ", v.CONF_THRESH);
    s << indent << "k_volleyball: ";
    Printer<int32_t>::stream(s, indent + "  ", v.k_volleyball);
    s << indent << "k_basketball: ";
    Printer<int32_t>::stream(s, indent + "  ", v.k_basketball);
    s << indent << "k_basket: ";
    Printer<int32_t>::stream(s, indent + "  ", v.k_basket);
    s << indent << "k_mark: ";
    Printer<int32_t>::stream(s, indent + "  ", v.k_mark);
    s << indent << "if_shot: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.if_shot);
    s << indent << "if_show: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.if_show);
    s << indent << "k_x0: ";
    Printer<double>::stream(s, indent + "  ", v.k_x0);
    s << indent << "k_y0: ";
    Printer<double>::stream(s, indent + "  ", v.k_y0);
    s << indent << "k_z0: ";
    Printer<double>::stream(s, indent + "  ", v.k_z0);
    s << indent << "k_x1: ";
    Printer<double>::stream(s, indent + "  ", v.k_x1);
    s << indent << "k_y1: ";
    Printer<double>::stream(s, indent + "  ", v.k_y1);
    s << indent << "k_z1: ";
    Printer<double>::stream(s, indent + "  ", v.k_z1);
    s << indent << "k_test: ";
    Printer<double>::stream(s, indent + "  ", v.k_test);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONFIG_MESSAGE_PARAM_H
